seed = 123456
device = "cpu"
task = "train"
model = "GraphUNet"
dataset = "rectangle_sin2"
pool = "topk"
d = 0.1
lr = 0.001
epochs = 5000
train_ratio = 0.0
test_ratio = 0.0
eval_every_eps = 5
physical_weight = 0.01
depth = 4
loss = "auto_weight"
physical_loss = "strong"
condense = "nn"
scheduler = "none"
use_pos = true