seed = 123456
device = "cuda"
task = "train"
model = "SIGN"
dataset = "rectangle_sin2_left"
d = 0.1
lr = 0.01
epochs = 100
train_ratio = 0.0
test_ratio = 0.0
eval_every_eps = 5
physical_weight = 0.01
num_hops = 8
loss = "auto_weight"
physical_loss = "strong"
condense = "nn"
scheduler = "cos"
use_pos = true
trainer = "multi"
encoder = "mlp"