seed = 123456
device = "cuda"
task = "train"
model = "SIGN"
dataset = "rectangle_sin2"
d = 0.1
lr = 0.001
epochs = 5000
train_ratio = 0.0
test_ratio = 0.0
eval_every_eps = 5
physical_weight = 0.01
num_hops = 8
loss = "auto_weight"
physical_loss = "strong"
condense = "nn_dense"
scheduler = "cos"
use_pos = true
encoder = 'mlp'