seed = 123456
device = "cuda"
task = "train"
model = "GAT"
dataset = "spherical_shell"
d = 0.2
use_condense = true
lr = 0.01
epochs = 1000
train_ratios = [ 0.05, 0.1, 0.2, 0.3, 0.5,]
test_ratio = 0.5
eval_every_eps = 5
