trainer = "multi"
seed = 123456
device = "cpu"
task = "train"
force = true
model = "NodeEdgeGNN"
dataset = "truss"
use_condense = false
lr = 0.01
epochs = 1000
train_ratios = [ 0.05, 0.1, 0.2, 0.3, 0.5,]
test_ratio = 0.5
eval_every_eps = 5
