seed = 123456
task = "test"
model = "NodeEdgeGNN"
dataset = "rectangle_sin2_left+right"
d = 0.1
train_ratios = [ 0.0, 0.1, 0.3,]
num_hops = 8
loss = "weight"
condense = "static"
physical_loss = "strong"
